In [2]:
import torch
torch.__version__

'2.5.1+cu124'

#### ***Arange Tensor:***

In [3]:
print(torch.arange.__doc__)


arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a 1-D tensor of size :math:`\left\lceil \frac{\text{end} - \text{start}}{\text{step}} \right\rceil`
with values from the interval ``[start, end)`` taken with common difference
:attr:`step` beginning from `start`.

Note that non-integer :attr:`step` is subject to floating point rounding errors when
comparing against :attr:`end`; to avoid inconsistency, we advise subtracting a small epsilon from :attr:`end`
in such cases.

.. math::
    \text{out}_{{i+1}} = \text{out}_{i} + \text{step}

Args:
    start (Number): the starting value for the set of points. Default: ``0``.
    end (Number): the ending value for the set of points
    step (Number): the gap between each pair of adjacent points. Default: ``1``.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        De

In [4]:
arange = torch.arange(start=10, end=20)
print(arange)
print(arange.dtype)
print(arange.shape)
print(arange.ndim)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
torch.int64
torch.Size([10])
1


In [5]:
arange = torch.arange(start=10, end=20, step=2)
print(arange)
print(arange.dtype)
print(arange.shape)
print(arange.ndim)

tensor([10, 12, 14, 16, 18])
torch.int64
torch.Size([5])
1


#### ***Like_tensor:***

In [6]:
one_like = torch.ones_like(arange)  # You can also pass the matrix as an argument
print(one_like)
print(one_like.dtype)
print(one_like.shape)
print(one_like.ndim)

tensor([1, 1, 1, 1, 1])
torch.int64
torch.Size([5])
1


In [7]:
zero_like = torch.zeros_like(arange)
print(zero_like)
print(zero_like.dtype)
print(zero_like.shape)
print(zero_like.ndim)

tensor([0, 0, 0, 0, 0])
torch.int64
torch.Size([5])
1


In [8]:
rand_like = torch.randn_like(arange, dtype=torch.float32)
print(rand_like)
print(rand_like.dtype)
print(rand_like.shape)
print(rand_like.ndim)

tensor([ 0.0394, -0.4049, -0.9461,  1.3050,  0.7274])
torch.float32
torch.Size([5])
1


In [9]:
rand_like = torch.rand_like(arange, dtype=torch.float32)
print(rand_like)
print(rand_like.dtype)
print(rand_like.shape)
print(rand_like.ndim)

tensor([0.1137, 0.9217, 0.9928, 0.0398, 0.1176])
torch.float32
torch.Size([5])
1


In [19]:
full_like = torch.full(size=(2, 3), fill_value=5)  # the argument values fill with the fill_value
print(full_like)
print(full_like.dtype)
print(full_like.shape)
print(full_like.ndim)

tensor([[5, 5, 5],
        [5, 5, 5]])
torch.int64
torch.Size([2, 3])
2


In [11]:
full_like = torch.full_like(arange, fill_value=5)  # the argument values fill with the fill_value
print(full_like)
print(full_like.dtype)
print(full_like.shape)
print(full_like.ndim)

tensor([5, 5, 5, 5, 5])
torch.int64
torch.Size([5])
1


In [12]:
print(torch.empty_like.__doc__)


empty_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns an uninitialized tensor with the same size as :attr:`input`.
``torch.empty_like(input)`` is equivalent to
``torch.empty(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

.. note::
    If :func:`torch.use_deterministic_algorithms()` and
    :attr:`torch.utils.deterministic.fill_uninitialized_memory` are both set to
    ``True``, the output tensor is initialized to prevent any possible
    nondeterministic behavior from using the data as an input to an operation.
    Floating point and complex tensors are filled with NaN, and integer tensors
    are filled with the maximum value.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype o

`torch.empty_like` is a PyTorch function that creates a new tensor with the same size, data type, and device as an existing tensor, but without initializing its elements to any specific values. This means the elements of the new tensor will contain `garbage` values.

In [13]:
empty = torch.empty(size=(2, 3))
print(empty)
print(empty.dtype)
print(empty.shape)
print(empty.ndim)

tensor([[1.6881e-33, 0.0000e+00, 1.6878e-33],
        [0.0000e+00, 1.5540e-42, 3.4199e+16]])
torch.float32
torch.Size([2, 3])
2


In [14]:
empty_like =  torch.empty_like(empty)
print(empty_like)
print(empty_like.dtype)
print(empty_like.shape)
print(empty_like.ndim)

tensor([[1.6894e-33, 0.0000e+00, 1.6911e-33],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
torch.float32
torch.Size([2, 3])
2


In [15]:
print(torch.randint_like.__doc__)


randint_like(input, low=0, high, \*, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor with the same shape as Tensor :attr:`input` filled with
random integers generated uniformly between :attr:`low` (inclusive) and
:attr:`high` (exclusive).

.. note:
    With the global dtype default (``torch.float32``), this function returns
    a tensor with dtype ``torch.int64``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor.
    low (int, optional): Lowest integer to be drawn from the distribution. Default: 0.
    high (int): One above the highest integer to be drawn from the distribution.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``

In [16]:
randiant = torch.randint(low=0, high=10, size=(2, 3))
print(randiant)
print(randiant.dtype)
print(randiant.shape)
print(randiant.ndim)

tensor([[8, 0, 4],
        [1, 0, 0]])
torch.int64
torch.Size([2, 3])
2


In [17]:
randiant_like = torch.randint_like(randiant, low=10, high=20)
print(randiant_like)
print(randiant_like.dtype)
print(randiant_like.shape)
print(randiant_like.ndim)

tensor([[11, 19, 15],
        [10, 13, 12]])
torch.int64
torch.Size([2, 3])
2


#### ***Eye:***

In [18]:
eye = torch.eye(n=3)
print(eye)
print(eye.dtype)
print(eye.shape)
print(eye.ndim)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.float32
torch.Size([3, 3])
2
