In [8]:
import torch
torch.__version__

'2.5.1+cu124'

#### ***Data Type:***

dtype is an attribute of a tensor that specifies the data type of its elements. Common data types include:

* torch.float32 (or torch.float): 32-bit floating-point numbers (default)
* torch.float64 (or torch.double): 64-bit floating-point numbers
* torch.int32 (or torch.int): 32-bit integers
* torch.int64 (or torch.long): 64-bit integers
* torch.bool: Boolean values (True or False)





None


In [9]:
rand_tesor = torch.rand(2, 3)
print(rand_tesor)
print(rand_tesor.dtype)

tensor([[0.1815, 0.3109, 0.3135],
        [0.6936, 0.6003, 0.0385]])
torch.float32


In [10]:
rand_tesor = torch.rand(2, 3, dtype=torch.float16)
print(rand_tesor)
print(rand_tesor.dtype)

tensor([[0.8267, 0.0537, 0.8340],
        [0.6226, 0.7832, 0.5020]], dtype=torch.float16)
torch.float16


In [12]:
rand_tesor = torch.rand(2, 3, dtype=torch.float16)
print(rand_tesor.to(dtype=torch.int32))


tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
