In [35]:
import torch
torch.__version__

'2.5.1+cu124'

#### ***MAX:***

In [58]:
print(torch.max.__doc__)


max(input) -> Tensor

Returns the maximum value of all elements in the ``input`` tensor.

.. warning::
    This function produces deterministic (sub)gradients unlike ``max(dim=0)``

Args:
    input (Tensor): the input tensor.

Example::

    >>> a = torch.randn(1, 3)
    >>> a
    tensor([[ 0.6763,  0.7445, -2.2369]])
    >>> torch.max(a)
    tensor(0.7445)

.. function:: max(input, dim, keepdim=False, *, out=None) -> (Tensor, LongTensor)
   :noindex:

Returns a namedtuple ``(values, indices)`` where ``values`` is the maximum
value of each row of the :attr:`input` tensor in the given dimension
:attr:`dim`. And ``indices`` is the index location of each maximum value found
(argmax).

If ``keepdim`` is ``True``, the output tensors are of the same size
as ``input`` except in the dimension ``dim`` where they are of size 1.
Otherwise, ``dim`` is squeezed (see :func:`torch.squeeze`), resulting
in the output tensors having 1 fewer dimension than ``input``.

.. note:: If there are multiple max

In [59]:
a_ten = torch.rand(3,3)

print(a_ten)


tensor([[0.1469, 0.6676, 0.4281],
        [0.4400, 0.9072, 0.7605],
        [0.1003, 0.5113, 0.7870]])


In [61]:
a_ten.max()


tensor(0.9072)

In [62]:
torch.max(a_ten)

tensor(0.9072)

In [64]:
torch.max(a_ten, dim=0)

torch.return_types.max(
values=tensor([0.4400, 0.9072, 0.7870]),
indices=tensor([1, 1, 2]))

In [65]:
torch.max(a_ten, dim=1)

torch.return_types.max(
values=tensor([0.6676, 0.9072, 0.7870]),
indices=tensor([1, 1, 2]))

#### ***Min:***

In [66]:
print(torch.min.__doc__)


min(input) -> Tensor

Returns the minimum value of all elements in the :attr:`input` tensor.

.. warning::
    This function produces deterministic (sub)gradients unlike ``min(dim=0)``

Args:
    input (Tensor): the input tensor.

Example::

    >>> a = torch.randn(1, 3)
    >>> a
    tensor([[ 0.6750,  1.0857,  1.7197]])
    >>> torch.min(a)
    tensor(0.6750)

.. function:: min(input, dim, keepdim=False, *, out=None) -> (Tensor, LongTensor)
   :noindex:

Returns a namedtuple ``(values, indices)`` where ``values`` is the minimum
value of each row of the :attr:`input` tensor in the given dimension
:attr:`dim`. And ``indices`` is the index location of each minimum value found
(argmin).

If :attr:`keepdim` is ``True``, the output tensors are of the same size as
:attr:`input` except in the dimension :attr:`dim` where they are of size 1.
Otherwise, :attr:`dim` is squeezed (see :func:`torch.squeeze`), resulting in
the output tensors having 1 fewer dimension than :attr:`input`.

.. note:: I

In [67]:
a_ten.min()

tensor(0.1003)

In [68]:
torch.min(a_ten)

tensor(0.1003)

In [69]:
torch.min(a_ten, dim=0)

torch.return_types.min(
values=tensor([0.1003, 0.5113, 0.4281]),
indices=tensor([2, 2, 0]))

In [70]:
torch.min(a_ten, dim=1)

torch.return_types.min(
values=tensor([0.1469, 0.4400, 0.1003]),
indices=tensor([0, 0, 0]))

#### ***Mean:***

In [71]:
print(torch.mean.__doc__)


mean(input, *, dtype=None) -> Tensor

Returns the mean value of all elements in the :attr:`input` tensor. Input must be floating point or complex.

Args:
    input (Tensor):
      the input tensor, either of floating point or complex dtype

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        If specified, the input tensor is casted to :attr:`dtype` before the operation
        is performed. This is useful for preventing data type overflows. Default: None.

Example::

    >>> a = torch.randn(1, 3)
    >>> a
    tensor([[ 0.2294, -0.5481,  1.3288]])
    >>> torch.mean(a)
    tensor(0.3367)

.. function:: mean(input, dim, keepdim=False, *, dtype=None, out=None) -> Tensor
   :noindex:

Returns the mean value of each row of the :attr:`input` tensor in the given
dimension :attr:`dim`. If :attr:`dim` is a list of dimensions,
reduce over all of them.


If :attr:`keepdim` is ``True``, the output tensor is of the same size
as :attr:`input`

In [72]:
a_ten.mean()

tensor(0.5277)

In [73]:
torch.mean(a_ten)

tensor(0.5277)

In [74]:
torch.mean(a_ten, dim=0)

tensor([0.2291, 0.6954, 0.6585])

In [75]:
torch.mean(a_ten, dim=1)

tensor([0.4142, 0.7025, 0.4662])

#### ***Sum:***

In [76]:
print(torch.sum.__doc__)


sum(input, *, dtype=None) -> Tensor

Returns the sum of all elements in the :attr:`input` tensor.

Args:
    input (Tensor): the input tensor.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        If specified, the input tensor is casted to :attr:`dtype` before the operation
        is performed. This is useful for preventing data type overflows. Default: None.

Example::

    >>> a = torch.randn(1, 3)
    >>> a
    tensor([[ 0.1133, -0.9567,  0.2958]])
    >>> torch.sum(a)
    tensor(-0.5475)

.. function:: sum(input, dim, keepdim=False, *, dtype=None) -> Tensor
   :noindex:

Returns the sum of each row of the :attr:`input` tensor in the given
dimension :attr:`dim`. If :attr:`dim` is a list of dimensions,
reduce over all of them.


If :attr:`keepdim` is ``True``, the output tensor is of the same size
as :attr:`input` except in the dimension(s) :attr:`dim` where it is of size 1.
Otherwise, :attr:`dim` is squeezed (see :func:`torch

In [79]:
torch.sum(a_ten)

tensor(4.7489)

In [80]:
torch.sum(a_ten, dim=0)

tensor([0.6872, 2.0861, 1.9756])

In [81]:
torch.sum(a_ten, dim=1)

tensor([1.2426, 2.1076, 1.3986])

In [86]:
torch.sum(a_ten, dim=0, keepdim=True)

tensor([[0.6872, 2.0861, 1.9756]])