In [1]:
import torch as th
th.__version__

'2.5.1+cu124'

In [7]:
# create random data
data = th.rand(3, 5)
print(data)
print(data.shape)
print(data.ndim)

tensor([[0.3830, 0.5518, 0.6317, 0.1570, 0.4577],
        [0.4907, 0.5443, 0.7391, 0.8222, 0.3461],
        [0.8728, 0.2327, 0.8219, 0.6698, 0.1092]])
torch.Size([3, 5])
2


In [12]:
print(th.rand.__doc__)


rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor

Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`

The shape of the tensor is defined by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the de

In [8]:
# Random tensor with `n` show is  normal distribution
data = th.randn(3, 5)
print(data)
print(data.shape)
print(data.ndim)

tensor([[ 1.2689, -1.5036, -1.1766,  0.0672,  0.7411],
        [ 1.0403,  1.1875,  0.2785,  1.4802, -0.7461],
        [ 1.8642, -0.3209, -0.1033,  1.4253, -0.9494]])
torch.Size([3, 5])
2


In [10]:
print(th.randn.__doc__)


randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor


Returns a tensor filled with random numbers from a normal distribution
with mean `0` and variance `1` (also called the standard normal
distribution).

.. math::
    \text{out}_{i} \sim \mathcal{N}(0, 1)

For complex dtypes, the tensor is i.i.d. sampled from a `complex normal distribution`_ with zero mean and
unit variance as

.. math::
    \text{out}_{i} \sim \mathcal{CN}(0, 1)

This is equivalent to separately sampling the real :math:`(\operatorname{Re})` and imaginary
:math:`(\operatorname{Im})` part of :math:`\text{out}_i` as

.. math::
    \operatorname{Re}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2}),\quad
    \operatorname{Im}(\text{out}_{i}) \sim \mathcal{N}(0, \frac{1}{2})

The shape of the tensor is defined by the variable argument :attr:`size`.


Args:
    size (int...): a sequence of integers defining the shape of the output tensor.

In [14]:
# Create the 3D tensor with 2 Matrix, 3 rows, and 5 columns
data = th.randn(2, 3, 5)
print(data)
print(data.shape)
print(data.ndim)

tensor([[[-0.0490,  1.1904, -1.4327,  0.7316,  0.2591],
         [ 0.2731, -0.5848, -3.2795,  0.1698,  0.3050],
         [ 0.1664, -0.0286,  1.1795, -0.2161,  0.2675]],

        [[-1.9350,  1.3430,  0.0277, -1.2253,  1.0242],
         [-0.5350,  1.7802, -2.9603, -0.6894,  0.5604],
         [ 1.0215, -0.6285,  0.1882,  0.5510,  0.0963]]])
torch.Size([2, 3, 5])
3
