In [2]:
import torch
torch.__version__

'2.5.1+cu124'

#### ***Reshape:***

In [3]:
print(torch.reshape.__doc__)


reshape(input, shape) -> Tensor

Returns a tensor with the same data and number of elements as :attr:`input`,
but with the specified shape. When possible, the returned tensor will be a view
of :attr:`input`. Otherwise, it will be a copy. Contiguous inputs and inputs
with compatible strides can be reshaped without copying, but you should not
depend on the copying vs. viewing behavior.

See :meth:`torch.Tensor.view` on when it is possible to return a view.

A single dimension may be -1, in which case it's inferred from the remaining
dimensions and the number of elements in :attr:`input`.

Args:
    input (Tensor): the tensor to be reshaped
    shape (tuple of int): the new shape

Example::

    >>> a = torch.arange(4.)
    >>> torch.reshape(a, (2, 2))
    tensor([[ 0.,  1.],
            [ 2.,  3.]])
    >>> b = torch.tensor([[0, 1], [2, 3]])
    >>> torch.reshape(b, (-1,))
    tensor([ 0,  1,  2,  3])



In [4]:
a_ten = torch.arange(1, 13)
print(a_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [5]:
a_ten.reshape(3, 4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [6]:
a_ten.reshape(4, 3)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [7]:
a_ten.reshape(2, 2, 3)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

#### ***View:***





In [8]:
print(a_ten.view.__doc__)


view(*shape) -> Tensor

Returns a new tensor with the same data as the :attr:`self` tensor but of a
different :attr:`shape`.

The returned tensor shares the same data and must have the same number
of elements, but may have a different size. For a tensor to be viewed, the new
view size must be compatible with its original size and stride, i.e., each new
view dimension must either be a subspace of an original dimension, or only span
across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
contiguity-like condition that :math:`\forall i = d, \dots, d+k-1`,

.. math::

  \text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]

Otherwise, it will not be possible to view :attr:`self` tensor as :attr:`shape`
without copying it (e.g., via :meth:`contiguous`). When it is unclear whether a
:meth:`view` can be performed, it is advisable to use :meth:`reshape`, which
returns a view if the shapes are compatible, and copies (equivalent to calling
:meth:`contiguous`) ot

In [9]:
print(a_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [10]:
a_ten.view(3, 4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [11]:
a_ten.view(3, 4)[0,0] = 100

In [12]:
a_ten

tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

#### ***Stack:***

In [13]:
tensor = torch.arange(1, 13)
print(tensor)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [14]:
torch.stack([tensor, a_ten, a_ten], dim=0)

tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
        [100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
        [100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12]])

In [15]:
torch.stack([tensor, a_ten, a_ten], dim=1)

tensor([[  1, 100, 100],
        [  2,   2,   2],
        [  3,   3,   3],
        [  4,   4,   4],
        [  5,   5,   5],
        [  6,   6,   6],
        [  7,   7,   7],
        [  8,   8,   8],
        [  9,   9,   9],
        [ 10,  10,  10],
        [ 11,  11,  11],
        [ 12,  12,  12]])

In [16]:
torch.stack([tensor, a_ten, a_ten], dim=1)

tensor([[  1, 100, 100],
        [  2,   2,   2],
        [  3,   3,   3],
        [  4,   4,   4],
        [  5,   5,   5],
        [  6,   6,   6],
        [  7,   7,   7],
        [  8,   8,   8],
        [  9,   9,   9],
        [ 10,  10,  10],
        [ 11,  11,  11],
        [ 12,  12,  12]])

#### ***UnSqueez:***

In [17]:
print(torch.unsqueeze.__doc__)


unsqueeze(input, dim) -> Tensor

Returns a new tensor with a dimension of size one inserted at the
specified position.

The returned tensor shares the same underlying data with this tensor.

A :attr:`dim` value within the range ``[-input.dim() - 1, input.dim() + 1)``
can be used. Negative :attr:`dim` will correspond to :meth:`unsqueeze`
applied at :attr:`dim` = ``dim + input.dim() + 1``.

Args:
    input (Tensor): the input tensor.
    dim (int): the index at which to insert the singleton dimension

Example::

    >>> x = torch.tensor([1, 2, 3, 4])
    >>> torch.unsqueeze(x, 0)
    tensor([[ 1,  2,  3,  4]])
    >>> torch.unsqueeze(x, 1)
    tensor([[ 1],
            [ 2],
            [ 3],
            [ 4]])



In [34]:
a_ten = torch.arange(1, 13)
print(a_ten)
print(a_ten.shape)
print(a_ten.ndim)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
1


In [35]:
a_ten_un = a_ten.unsqueeze(0)
print(a_ten_un)
print(a_ten_un.shape)
print(a_ten_un.ndim)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])
2


In [36]:
a_ten_un_1 = a_ten.unsqueeze(1)
print(a_ten_un_1)
print(a_ten_un_1.shape)
print(a_ten_un_1.ndim)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
torch.Size([12, 1])
2


#### ***Squeez:***

In [37]:
print(torch.squeeze.__doc__)


squeeze(input, dim=None) -> Tensor

Returns a tensor with all specified dimensions of :attr:`input` of size `1` removed.

For example, if `input` is of shape:
:math:`(A \times 1 \times B \times C \times 1 \times D)` then the `input.squeeze()`
will be of shape: :math:`(A \times B \times C \times D)`.

When :attr:`dim` is given, a squeeze operation is done only in the given
dimension(s). If `input` is of shape: :math:`(A \times 1 \times B)`,
``squeeze(input, 0)`` leaves the tensor unchanged, but ``squeeze(input, 1)``
will squeeze the tensor to the shape :math:`(A \times B)`.

.. note:: The returned tensor shares the storage with the input tensor,
          so changing the contents of one will change the contents of the other.

.. warning:: If the tensor has a batch dimension of size 1, then `squeeze(input)`
          will also remove the batch dimension, which can lead to unexpected
          errors. Consider specifying only the dims you wish to be squeezed.

Args:
    input (Tensor): t

In [38]:
a_ten_sq = a_ten_un.squeeze()
print(a_ten_sq)
print(a_ten_sq.shape)
print(a_ten_sq.ndim)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
1


In [39]:
a_ten_sq_1 = a_ten_un_1.squeeze()
print(a_ten_sq_1)
print(a_ten_sq_1.shape)
print(a_ten_sq_1.ndim)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
1


#### ***Permut:***

In [40]:
print(torch.permute.__doc__)


permute(input, dims) -> Tensor

Returns a view of the original tensor :attr:`input` with its dimensions permuted.

Args:
    input (Tensor): the input tensor.
    dims (tuple of int): The desired ordering of dimensions

Example:
    >>> x = torch.randn(2, 3, 5)
    >>> x.size()
    torch.Size([2, 3, 5])
    >>> torch.permute(x, (2, 0, 1)).size()
    torch.Size([5, 2, 3])



In [41]:
rand = torch.randn(2, 3, 5)
print(rand)
print(rand.shape)
print(rand.ndim)

tensor([[[ 0.1742,  0.0913, -0.0557,  0.4748, -2.7716],
         [ 0.7739,  0.2739, -0.0876, -2.0577, -2.1510],
         [ 0.0903,  0.3945, -2.1239, -0.8232,  0.5906]],

        [[-1.5474, -1.5575,  1.1503,  0.0698, -0.9631],
         [ 1.3978,  0.0105, -0.2382, -0.8204, -1.2301],
         [ 1.1082,  0.8407,  0.5174, -0.0237,  0.3775]]])
torch.Size([2, 3, 5])
3


In [42]:
rand.permute(2, 0, 1)

tensor([[[ 0.1742,  0.7739,  0.0903],
         [-1.5474,  1.3978,  1.1082]],

        [[ 0.0913,  0.2739,  0.3945],
         [-1.5575,  0.0105,  0.8407]],

        [[-0.0557, -0.0876, -2.1239],
         [ 1.1503, -0.2382,  0.5174]],

        [[ 0.4748, -2.0577, -0.8232],
         [ 0.0698, -0.8204, -0.0237]],

        [[-2.7716, -2.1510,  0.5906],
         [-0.9631, -1.2301,  0.3775]]])