In [1]:
import torch
torch.__version__

'2.5.1+cu124'

### ***scalar*** :

In [2]:
# create the variable in tensor this is the scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# check the dismisson of varible
scalar.ndim

0

In [4]:
# check the itme of varible
scalar.item()

7

In [5]:
# check the shape of data type
scalar.shape

torch.Size([])

In [6]:
# check the varible data type
scalar.dtype

torch.int64

In [7]:
# change the data type of varible
scalar.to(torch.float32)

tensor(7.)

### ***vector***:

In [9]:
# create the variable in tensor this is the vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
# check the dismisson of vector
vector.ndim

1

In [11]:
# check the shape of vector
vector.shape

torch.Size([2])

### ***Matrix***:

In [13]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
matrix.ndim

2

### ***Tensor With 3-D:***  
**[2, 3, 3]**

*   **`2`** Show the Number of matrix in Tensor
*   **`3 and 3`** show the shape of the matrix in tensor

In [32]:
tensor_ = torch.tensor([
                          [[1,2,3],
                           [4,5,6],
                           [7,8,9]],
                          [[0,1,2],
                           [14,5,0],
                           [72,80,9]]
                         ])
tensor_

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 0,  1,  2],
         [14,  5,  0],
         [72, 80,  9]]])

In [33]:
tensor_.ndim

3

In [34]:
tensor_.shape

torch.Size([2, 3, 3])

#### ***Tensor With 4-D :***

**`[2, 1, 3, 3]`**

*  2 (1st dimension): Represents the total number of matrices within the 4D tensor. You have 2 main matrices.

*  1 (2nd dimension): Indicates that each of the 2 main matrices contains 1 sub-matrix or layer. Think of it as having a single "slice" within each main matrix.

*  3 and 3 (3rd and 4th dimensions): Define the shape or dimensions of the sub-matrices (and the main matrices as well). Each sub-matrix (and main matrix) is a 3x3 matrix.





In [47]:
tensor_4 = torch.tensor([[
                          [[1,2,3],
                           [4,5,6],
                           [7,8,9]],
                         ],[
                          [[1,2,3],
                           [4,5,6],
                           [7,8,9]],
                          ]
                         ])
tensor_4

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [48]:
tensor_4.ndim

4

In [49]:
tensor_4.shape

torch.Size([2, 1, 3, 3])