In [35]:
import torch
torch.__version__

'2.5.1+cu124'

#### ***Addition:***

In [51]:
print(torch.add.__doc__)


add(input, other, *, alpha=1, out=None) -> Tensor

Adds :attr:`other`, scaled by :attr:`alpha`, to :attr:`input`.

.. math::
    \text{{out}}_i = \text{{input}}_i + \text{{alpha}} \times \text{{other}}_i


Supports :ref:`broadcasting to a common shape <broadcasting-semantics>`,
:ref:`type promotion <type-promotion-doc>`, and integer, float, and complex inputs.

Args:
    input (Tensor): the input tensor.
    other (Tensor or Number): the tensor or number to add to :attr:`input`.

Keyword arguments:
    alpha (Number): the multiplier for :attr:`other`.
    out (Tensor, optional): the output tensor.

Examples::

    >>> a = torch.randn(4)
    >>> a
    tensor([ 0.0202,  1.0985,  1.3506, -0.6056])
    >>> torch.add(a, 20)
    tensor([ 20.0202,  21.0985,  21.3506,  19.3944])

    >>> b = torch.randn(4)
    >>> b
    tensor([-0.9732, -0.3497,  0.6245,  0.4022])
    >>> c = torch.randn(4, 1)
    >>> c
    tensor([[ 0.3743],
            [-1.7724],
            [-0.5811],
            [-0.8017]

In [36]:
a_ten = torch.rand(3,3)
b_ten = torch.rand(3,3)
print(a_ten)
print(b_ten)

tensor([[0.3566, 0.3438, 0.9721],
        [0.6952, 0.5105, 0.1676],
        [0.8754, 0.4529, 0.0531]])
tensor([[0.6180, 0.5561, 0.8785],
        [0.2979, 0.8358, 0.5954],
        [0.7297, 0.8821, 0.7257]])


In [40]:
a_ten + b_ten

tensor([[0.9746, 0.8999, 1.8506],
        [0.9931, 1.3463, 0.7630],
        [1.6050, 1.3350, 0.7788]])

In [41]:
torch.add(a_ten, b_ten)

tensor([[0.9746, 0.8999, 1.8506],
        [0.9931, 1.3463, 0.7630],
        [1.6050, 1.3350, 0.7788]])

#### ***Subtraction:***

In [52]:
print(torch.sub.__doc__)


sub(input, other, *, alpha=1, out=None) -> Tensor

Subtracts :attr:`other`, scaled by :attr:`alpha`, from :attr:`input`.

.. math::
    \text{{out}}_i = \text{{input}}_i - \text{{alpha}} \times \text{{other}}_i


Supports :ref:`broadcasting to a common shape <broadcasting-semantics>`,
:ref:`type promotion <type-promotion-doc>`, and integer, float, and complex inputs.

Args:
    input (Tensor): the input tensor.
    other (Tensor or Number): the tensor or number to subtract from :attr:`input`.

Keyword args:
    alpha (Number): the multiplier for :attr:`other`.
    out (Tensor, optional): the output tensor.

Example::

    >>> a = torch.tensor((1, 2))
    >>> b = torch.tensor((0, 1))
    >>> torch.sub(a, b, alpha=2)
    tensor([1, 0])



In [42]:
a_ten - b_ten

tensor([[-0.2614, -0.2123,  0.0936],
        [ 0.3973, -0.3253, -0.4277],
        [ 0.1457, -0.4292, -0.6727]])

In [43]:
torch.sub(a_ten, b_ten)

tensor([[-0.2614, -0.2123,  0.0936],
        [ 0.3973, -0.3253, -0.4277],
        [ 0.1457, -0.4292, -0.6727]])

#### ***Multiplication:***

In [53]:
print(torch.mul.__doc__)


mul(input, other, *, out=None) -> Tensor

Multiplies :attr:`input` by :attr:`other`.


.. math::
    \text{out}_i = \text{input}_i \times \text{other}_i


Supports :ref:`broadcasting to a common shape <broadcasting-semantics>`,
:ref:`type promotion <type-promotion-doc>`, and integer, float, and complex inputs.

Args:
    input (Tensor): the input tensor.
    other (Tensor or Number) - the tensor or number to multiply input by.

Keyword args:
    out (Tensor, optional): the output tensor.

Examples::

    >>> a = torch.randn(3)
    >>> a
    tensor([ 0.2015, -0.4255,  2.6087])
    >>> torch.mul(a, 100)
    tensor([  20.1494,  -42.5491,  260.8663])

    >>> b = torch.randn(4, 1)
    >>> b
    tensor([[ 1.1207],
            [-0.3137],
            [ 0.0700],
            [ 0.8378]])
    >>> c = torch.randn(1, 4)
    >>> c
    tensor([[ 0.5146,  0.1216, -0.5244,  2.2382]])
    >>> torch.mul(b, c)
    tensor([[ 0.5767,  0.1363, -0.5877,  2.5083],
            [-0.1614, -0.0382,  0.1645, -0.70

In [44]:
a_ten * b_ten

tensor([[0.2204, 0.1912, 0.8539],
        [0.2071, 0.4267, 0.0998],
        [0.6387, 0.3995, 0.0385]])

In [45]:
torch.mul(a_ten, b_ten)

tensor([[0.2204, 0.1912, 0.8539],
        [0.2071, 0.4267, 0.0998],
        [0.6387, 0.3995, 0.0385]])

#### ***Division:***

In [54]:
print(torch.div.__doc__)


div(input, other, *, rounding_mode=None, out=None) -> Tensor

Divides each element of the input ``input`` by the corresponding element of
:attr:`other`.

.. math::
    \text{out}_i = \frac{\text{input}_i}{\text{other}_i}

.. note::
    By default, this performs a "true" division like Python 3.
    See the :attr:`rounding_mode` argument for floor division.

Supports :ref:`broadcasting to a common shape <broadcasting-semantics>`,
:ref:`type promotion <type-promotion-doc>`, and integer, float, and complex inputs.
Always promotes integer types to the default scalar type.

Args:
    input (Tensor): the dividend
    other (Tensor or Number): the divisor

Keyword args:
    rounding_mode (str, optional): Type of rounding applied to the result:

        * None - default behavior. Performs no rounding and, if both :attr:`input` and
          :attr:`other` are integer types, promotes the inputs to the default scalar type.
          Equivalent to true division in Python (the ``/`` operator) and N

In [46]:
a_ten / b_ten

tensor([[0.5771, 0.6182, 1.1066],
        [2.3338, 0.6108, 0.2816],
        [1.1996, 0.5134, 0.0731]])

In [47]:
torch.div(a_ten, b_ten)

tensor([[0.5771, 0.6182, 1.1066],
        [2.3338, 0.6108, 0.2816],
        [1.1996, 0.5134, 0.0731]])

#### ***Matrux multiptication:***

In [55]:
print(torch.matmul.__doc__)


matmul(input, other, *, out=None) -> Tensor

Matrix product of two tensors.

The behavior depends on the dimensionality of the tensors as follows:

- If both tensors are 1-dimensional, the dot product (scalar) is returned.
- If both arguments are 2-dimensional, the matrix-matrix product is returned.
- If the first argument is 1-dimensional and the second argument is 2-dimensional,
  a 1 is prepended to its dimension for the purpose of the matrix multiply.
  After the matrix multiply, the prepended dimension is removed.
- If the first argument is 2-dimensional and the second argument is 1-dimensional,
  the matrix-vector product is returned.
- If both arguments are at least 1-dimensional and at least one argument is
  N-dimensional (where N > 2), then a batched matrix multiply is returned.  If the first
  argument is 1-dimensional, a 1 is prepended to its dimension for the purpose of the
  batched matrix multiply and removed after.  If the second argument is 1-dimensional, a
  1 is app

In [48]:
a_ten @ b_ten

tensor([[1.0321, 1.3431, 1.2234],
        [0.7040, 0.9611, 1.0363],
        [0.7146, 0.9121, 1.0771]])

In [50]:
torch.matmul(a_ten, b_ten)

tensor([[1.0321, 1.3431, 1.2234],
        [0.7040, 0.9611, 1.0363],
        [0.7146, 0.9121, 1.0771]])

In [56]:
a = torch.randn_like(a_ten)
b = torch.randn_like(a_ten)

In [57]:
a.matmul(b)

tensor([[ 0.0885,  0.0451,  0.1910],
        [-1.8015, -0.0083, -0.0930],
        [ 0.0121, -0.1046,  1.9451]])