In [1]:
import torch as th
th.__version__

'2.5.1+cu124'

### ***Zeros:***

In [2]:
# create random data
data = th.zeros(1, 5)
print(data)
print(data.shape)
print(data.ndim)

tensor([[0., 0., 0., 0., 0.]])
torch.Size([1, 5])
2


In [3]:
print(th.zeros.__doc__)


zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `0`, with the shape defined
by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func:`torch.set_default_device`). :attr:`device` will be the CPU
 

In [4]:
# Random tensor with `n` show is  normal distribution
data = th.zeros(3, 5)
print(data)
print(data.shape)
print(data.ndim)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([3, 5])
2


In [5]:
# Create the 3D tensor with 2 Matrix, 3 rows, and 5 columns
data = th.zeros(2, 3, 5)
print(data)
print(data.shape)
print(data.ndim)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.Size([2, 3, 5])
3


In [6]:
data = th.randn_like(data)
print(data)
print(data.shape)
print(data.ndim)

tensor([[[ 1.6851,  0.1561,  1.3276, -1.0184, -0.1824],
         [-0.5310, -0.7835,  0.1598, -0.6568, -0.0936],
         [ 1.7321,  0.9621,  0.8935,  0.2943, -0.3318]],

        [[-1.5730,  0.6019,  1.0474,  0.5833,  0.2483],
         [-0.7769, -0.1593,  0.9774, -0.5759,  2.3043],
         [ 0.5602, -1.0935,  0.4560,  1.7659, -1.0794]]])
torch.Size([2, 3, 5])
3


In [7]:

zero_like = th.zeros_like(data)
print(zero_like)
print(zero_like.shape)
print(zero_like.ndim)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.Size([2, 3, 5])
3


### ***Ones:***

In [8]:
ones = th.ones([5])
print(ones)
print(ones.shape)
print(ones.ndim)

tensor([1., 1., 1., 1., 1.])
torch.Size([5])
1


In [9]:
print(th.ones.__doc__)


ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `1`, with the shape defined
by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword arguments:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func:`torch.set_default_device`). :attr:`device` will be the C

In [10]:
one_likes = th.ones_like(data)
print(one_likes)
print(one_likes.shape)
print(one_likes.ndim)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
torch.Size([2, 3, 5])
3


In [11]:
print(th.ones_like.__doc__)


ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor

Returns a tensor filled with the scalar value `1`, with the same size as
:attr:`input`. ``torch.ones_like(input)`` is equivalent to
``torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

.. warning::
    As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
    the old ``torch.ones_like(input, out=output)`` is equivalent to
    ``torch.ones(input.size(), out=output)``.

Args:
    input (Tensor): the size of :attr:`input` will determine size of the output tensor.

Keyword arguments:
    dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
        Default: if ``None``, defaults to the dtype of :attr:`input`.
    layout (:class:`torch.layout`, optional): the desired layout of returned tensor.
        Default: if ``None``, defaults to the layout of :attr:`input`.
    d